services:
  api:
    # Locally built image:
    image: minitwit-api:dev
    environment:
      - DATABASE_PATH=${DATABASE_PATH:-postgresql://myuser:mypassword@db:5432/mydb}
      - LOG_LEVEL=${LOG_LEVEL}
      - SIMULATOR_AUTH=${SIMULATOR_AUTH}
    networks:
      - minitwit-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  web:
    # Locally built image:
    image: minitwit-web:dev
    environment:
      - DATABASE_PATH=${DATABASE_PATH:-postgresql://myuser:mypassword@db:5432/mydb}
      - LOG_LEVEL=${LOG_LEVEL}
      - SIMULATOR_AUTH=${SIMULATOR_AUTH}
    networks:
      - minitwit-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  nginx:
    image: nginx:latest
    ports:
      - target: 80
        published: 80
    volumes:
      - ./nginx.develop.conf:/etc/nginx/nginx.conf:ro
    networks:
      - minitwit-network
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:  # Network shared between services so we can refer to them by name
  minitwit-network:
    external: true
    name: minitwit-network

