FROM golang:1.25

WORKDIR /app

# Install libsqlite3 which is needed for the application
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libc6-dev libsqlite3-dev \
 && rm -rf /var/lib/apt/lists/*

# Copy and download go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy our Go source code
COPY . .

# Build API
RUN CGO_ENABLED=1 GOOS=linux go build -o api ./cmd/api

EXPOSE 5001

CMD ["./api"]