services:
  minitwit-app:
    image: marcp85/minitwitimage:latest #Changed to match Docker Hub image name
    ports:
      - "5001:5001"
    volumes:
      - /data:/data
    environment:
      - DATABASE_PATH=/data/minitwit.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 30s
      timeout: 10s
      retries: 3

  minitwit-tests:
    image: minitwittestimage:latest
    build:
      context: .
      dockerfile: Dockerfile-minitwit-tests
    depends_on:
      minitwit-app:
        condition: service_healthy
    environment:
      - FRONTEND_URL=http://minitwit-app:5001
