FROM python:3.12-alpine

RUN mkdir /minitwit-tests

COPY minitwit_tests.py /minitwit-tests/
COPY requirements.txt /minitwit-tests/

WORKDIR /minitwit-tests

RUN pip install -r requirements.txt

EXPOSE 5001

ENTRYPOINT ["pytest", "-s", "minitwit_tests.py"]