services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - minitwit-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SERVER_ROOT_URL=https://minitwit-devops.tech/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    depends_on:
      - prometheus
      - loki
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-storage:/var/lib/grafana
    networks:
      - minitwit-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  loki:
    image: grafana/loki:latest
    volumes:
      - loki-storage:/loki
      - ./loki/loki-config.yml:/mnt/config/loki-config.yml  # Mount the loki config file
    command: -config.file=/mnt/config/loki-config.yml -target=all
    networks:
      - minitwit-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail/promtail-config.yml:/mnt/config/promtail-config.yml  # Mount the promtail config file
      - /var/run/docker.sock:/var/run/docker.sock                        # Mounting the docker socket
      - /var/lib/docker/containers:/var/lib/docker/containers:ro         # Mounting the log directory from host
    command: -config.file=/mnt/config/promtail-config.yml
    depends_on:
      - loki
    networks:
      - minitwit-network
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

networks:  # Network shared between services so we can refer to them by name
  minitwit-network:
    external: true
    name: minitwit-network


volumes:
  grafana-storage:
  loki-storage: