services:
  api:
    build: .
    container_name: minitwit-api
    ports:
      - "5001:5001"
    environment:
      DATABASE_PATH: ${DATABASE_PATH}
      LOG_LEVEL: ${LOG_LEVEL}
      SIMULATOR_AUTH: ${SIMULATOR_AUTH}
    command: ./api
    networks:
      - minitwit-network
    restart: unless-stopped

  web:
    build: .
    container_name: minitwit-web
    ports:
      - "5000:5000"
    environment:
      API_BASE_URL: http://api:5001/
      SESSION_KEY: ${SESSION_KEY}
    command: ./web
    depends_on:
      - api
    networks:
      - minitwit-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api
      - web
    networks:
      - minitwit-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - grafana-storage:/var/lib/grafana
    networks:
      - minitwit-network
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - loki-storage:/loki
      - ./loki/loki-config.yml:/mnt/config/loki-config.yml
    command: -config.file=/mnt/config/loki-config.yml
    ports:
      - "3100:3100"
    networks:
      - minitwit-network
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yml:/mnt/config/promtail-config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/mnt/config/promtail-config.yml
    depends_on:
      - loki
    networks:
      - minitwit-network
    restart: unless-stopped

networks:
  minitwit-network:
    name: minitwit-network
    driver: bridge

volumes:
  grafana-storage:
  loki-storage: