services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: minitwit_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d minitwit_test"]
      interval: 5s
      timeout: 3s
      retries: 30
  api:
    # Locally built image:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: minitwitapiimage:local
    container_name: minitwit-api
    ports:
      - "5001:5001"
    environment:
      - DATABASE_PATH=${DATABASE_PATH_DOCKER}
      - SIMULATOR_AUTH=${SIMULATOR_AUTH}
    networks:
      - minitwit-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    # Locally built image:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: minitwitwebimage:local
    container_name: minitwit-web
    ports:
      - "5000:5000"
    environment:
      - DATABASE_PATH=${DATABASE_PATH_DOCKER}
      - SIMULATOR_AUTH=${SIMULATOR_AUTH}
    networks:
      - minitwit-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3


networks:  # Network shared between services so we can refer to them by name
  minitwit-network:
    external: false
    name: minitwit-network