// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Minitwit API
 *
 * Minitwit API
 *
 * API version: 1.0
 */

package openapi

import (
	"context"
	"net/http"
)



// MinitwitAPIRouter defines the required methods for binding the api requests to a responses for the MinitwitAPI
// The MinitwitAPIRouter implementation should parse necessary information from the http request,
// pass the data to a MinitwitAPIServicer to perform the required actions, then write the service results to the http response.
type MinitwitAPIRouter interface { 
	GetFollow(http.ResponseWriter, *http.Request)
	PostFollow(http.ResponseWriter, *http.Request)
	GetLatestValue(http.ResponseWriter, *http.Request)
	GetMessages(http.ResponseWriter, *http.Request)
	GetMessagesPerUser(http.ResponseWriter, *http.Request)
	PostMessagesPerUser(http.ResponseWriter, *http.Request)
	PostRegister(http.ResponseWriter, *http.Request)
}


// MinitwitAPIServicer defines the api actions for the MinitwitAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type MinitwitAPIServicer interface { 
	GetFollow(context.Context, string, string, int32, int32) (ImplResponse, error)
	PostFollow(context.Context, string, string, FollowAction, int32) (ImplResponse, error)
	GetLatestValue(context.Context) (ImplResponse, error)
	GetMessages(context.Context, string, int32, int32) (ImplResponse, error)
	GetMessagesPerUser(context.Context, string, string, int32, int32) (ImplResponse, error)
	PostMessagesPerUser(context.Context, string, string, PostMessage, int32) (ImplResponse, error)
	PostRegister(context.Context, RegisterRequest, int32) (ImplResponse, error)
}
