// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Minitwit API
 *
 * Minitwit API
 *
 * API version: 1.0
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// MinitwitAPIService is a service that implements the logic for the MinitwitAPIServicer
// This service should implement the business logic for every endpoint for the MinitwitAPI API.
// Include any external packages or services that will be required by this service.
type MinitwitAPIService struct {
}

// NewMinitwitAPIService creates a default api service
func NewMinitwitAPIService() *MinitwitAPIService {
	return &MinitwitAPIService{}
}

// GetFollow - 
func (s *MinitwitAPIService) GetFollow(ctx context.Context, username string, authorization string, latest int32, no int32) (ImplResponse, error) {
	// TODO - update GetFollow with the required logic for this service method.
	// Add api_minitwit_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, FollowsResponse{}) or use other options such as http.Ok ...
	// return Response(200, FollowsResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(403, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetFollow method not implemented")
}

// PostFollow - 
func (s *MinitwitAPIService) PostFollow(ctx context.Context, username string, authorization string, payload FollowAction, latest int32) (ImplResponse, error) {
	// TODO - update PostFollow with the required logic for this service method.
	// Add api_minitwit_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(403, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("PostFollow method not implemented")
}

// GetLatestValue - 
func (s *MinitwitAPIService) GetLatestValue(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetLatestValue with the required logic for this service method.
	// Add api_minitwit_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, LatestValue{}) or use other options such as http.Ok ...
	// return Response(200, LatestValue{}), nil

	// TODO: Uncomment the next line to return response Response(500, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(500, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetLatestValue method not implemented")
}

// GetMessages - 
func (s *MinitwitAPIService) GetMessages(ctx context.Context, authorization string, latest int32, no int32) (ImplResponse, error) {
	// TODO - update GetMessages with the required logic for this service method.
	// Add api_minitwit_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Message{}) or use other options such as http.Ok ...
	// return Response(200, []Message{}), nil

	// TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(403, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetMessages method not implemented")
}

// GetMessagesPerUser - 
func (s *MinitwitAPIService) GetMessagesPerUser(ctx context.Context, username string, authorization string, latest int32, no int32) (ImplResponse, error) {
	// TODO - update GetMessagesPerUser with the required logic for this service method.
	// Add api_minitwit_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Message{}) or use other options such as http.Ok ...
	// return Response(200, []Message{}), nil

	// TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(403, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetMessagesPerUser method not implemented")
}

// PostMessagesPerUser - 
func (s *MinitwitAPIService) PostMessagesPerUser(ctx context.Context, username string, authorization string, payload PostMessage, latest int32) (ImplResponse, error) {
	// TODO - update PostMessagesPerUser with the required logic for this service method.
	// Add api_minitwit_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(403, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("PostMessagesPerUser method not implemented")
}

// PostRegister - 
func (s *MinitwitAPIService) PostRegister(ctx context.Context, payload RegisterRequest, latest int32) (ImplResponse, error) {
	// TODO - update PostRegister with the required logic for this service method.
	// Add api_minitwit_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(400, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("PostRegister method not implemented")
}
