// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Minitwit API
 *
 * Minitwit API
 *
 * API version: 1.0
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// MinitwitAPIController binds http requests to an api service and writes the service results to the http response
type MinitwitAPIController struct {
	service MinitwitAPIServicer
	errorHandler ErrorHandler
}

// MinitwitAPIOption for how the controller is set up.
type MinitwitAPIOption func(*MinitwitAPIController)

// WithMinitwitAPIErrorHandler inject ErrorHandler into controller
func WithMinitwitAPIErrorHandler(h ErrorHandler) MinitwitAPIOption {
	return func(c *MinitwitAPIController) {
		c.errorHandler = h
	}
}

// NewMinitwitAPIController creates a default api controller
func NewMinitwitAPIController(s MinitwitAPIServicer, opts ...MinitwitAPIOption) *MinitwitAPIController {
	controller := &MinitwitAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the MinitwitAPIController
func (c *MinitwitAPIController) Routes() Routes {
	return Routes{
		"GetFollow": Route{
			"GetFollow",
			strings.ToUpper("Get"),
			"/fllws/{username}",
			c.GetFollow,
		},
		"PostFollow": Route{
			"PostFollow",
			strings.ToUpper("Post"),
			"/fllws/{username}",
			c.PostFollow,
		},
		"GetLatestValue": Route{
			"GetLatestValue",
			strings.ToUpper("Get"),
			"/latest",
			c.GetLatestValue,
		},
		"GetMessages": Route{
			"GetMessages",
			strings.ToUpper("Get"),
			"/msgs",
			c.GetMessages,
		},
		"GetMessagesPerUser": Route{
			"GetMessagesPerUser",
			strings.ToUpper("Get"),
			"/msgs/{username}",
			c.GetMessagesPerUser,
		},
		"PostMessagesPerUser": Route{
			"PostMessagesPerUser",
			strings.ToUpper("Post"),
			"/msgs/{username}",
			c.PostMessagesPerUser,
		},
		"PostRegister": Route{
			"PostRegister",
			strings.ToUpper("Post"),
			"/register",
			c.PostRegister,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the MinitwitAPIController
func (c *MinitwitAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"GetFollow",
			strings.ToUpper("Get"),
			"/fllws/{username}",
			c.GetFollow,
		},
		Route{
			"PostFollow",
			strings.ToUpper("Post"),
			"/fllws/{username}",
			c.PostFollow,
		},
		Route{
			"GetLatestValue",
			strings.ToUpper("Get"),
			"/latest",
			c.GetLatestValue,
		},
		Route{
			"GetMessages",
			strings.ToUpper("Get"),
			"/msgs",
			c.GetMessages,
		},
		Route{
			"GetMessagesPerUser",
			strings.ToUpper("Get"),
			"/msgs/{username}",
			c.GetMessagesPerUser,
		},
		Route{
			"PostMessagesPerUser",
			strings.ToUpper("Post"),
			"/msgs/{username}",
			c.PostMessagesPerUser,
		},
		Route{
			"PostRegister",
			strings.ToUpper("Post"),
			"/register",
			c.PostRegister,
		},
	}
}



// GetFollow - 
func (c *MinitwitAPIController) GetFollow(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	usernameParam := params["username"]
	if usernameParam == "" {
		c.errorHandler(w, r, &RequiredError{"username"}, nil)
		return
	}
	authorizationParam := r.Header.Get("Authorization")
	var latestParam int32
	if query.Has("latest") {
		param, err := parseNumericParameter[int32](
			query.Get("latest"),
			WithParse[int32](parseInt32),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "latest", Err: err}, nil)
			return
		}

		latestParam = param
	} else {
	}
	var noParam int32
	if query.Has("no") {
		param, err := parseNumericParameter[int32](
			query.Get("no"),
			WithParse[int32](parseInt32),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "no", Err: err}, nil)
			return
		}

		noParam = param
	} else {
		var param int32 = 100
		noParam = param
	}
	result, err := c.service.GetFollow(r.Context(), usernameParam, authorizationParam, latestParam, noParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// PostFollow - 
func (c *MinitwitAPIController) PostFollow(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	usernameParam := params["username"]
	if usernameParam == "" {
		c.errorHandler(w, r, &RequiredError{"username"}, nil)
		return
	}
	authorizationParam := r.Header.Get("Authorization")
	var payloadParam FollowAction
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&payloadParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertFollowActionRequired(payloadParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertFollowActionConstraints(payloadParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	var latestParam int32
	if query.Has("latest") {
		param, err := parseNumericParameter[int32](
			query.Get("latest"),
			WithParse[int32](parseInt32),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "latest", Err: err}, nil)
			return
		}

		latestParam = param
	} else {
	}
	result, err := c.service.PostFollow(r.Context(), usernameParam, authorizationParam, payloadParam, latestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetLatestValue - 
func (c *MinitwitAPIController) GetLatestValue(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetLatestValue(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetMessages - 
func (c *MinitwitAPIController) GetMessages(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	authorizationParam := r.Header.Get("Authorization")
	var latestParam int32
	if query.Has("latest") {
		param, err := parseNumericParameter[int32](
			query.Get("latest"),
			WithParse[int32](parseInt32),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "latest", Err: err}, nil)
			return
		}

		latestParam = param
	} else {
	}
	var noParam int32
	if query.Has("no") {
		param, err := parseNumericParameter[int32](
			query.Get("no"),
			WithParse[int32](parseInt32),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "no", Err: err}, nil)
			return
		}

		noParam = param
	} else {
		var param int32 = 100
		noParam = param
	}
	result, err := c.service.GetMessages(r.Context(), authorizationParam, latestParam, noParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetMessagesPerUser - 
func (c *MinitwitAPIController) GetMessagesPerUser(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	usernameParam := params["username"]
	if usernameParam == "" {
		c.errorHandler(w, r, &RequiredError{"username"}, nil)
		return
	}
	authorizationParam := r.Header.Get("Authorization")
	var latestParam int32
	if query.Has("latest") {
		param, err := parseNumericParameter[int32](
			query.Get("latest"),
			WithParse[int32](parseInt32),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "latest", Err: err}, nil)
			return
		}

		latestParam = param
	} else {
	}
	var noParam int32
	if query.Has("no") {
		param, err := parseNumericParameter[int32](
			query.Get("no"),
			WithParse[int32](parseInt32),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "no", Err: err}, nil)
			return
		}

		noParam = param
	} else {
		var param int32 = 100
		noParam = param
	}
	result, err := c.service.GetMessagesPerUser(r.Context(), usernameParam, authorizationParam, latestParam, noParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// PostMessagesPerUser - 
func (c *MinitwitAPIController) PostMessagesPerUser(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	usernameParam := params["username"]
	if usernameParam == "" {
		c.errorHandler(w, r, &RequiredError{"username"}, nil)
		return
	}
	authorizationParam := r.Header.Get("Authorization")
	var payloadParam PostMessage
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&payloadParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertPostMessageRequired(payloadParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertPostMessageConstraints(payloadParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	var latestParam int32
	if query.Has("latest") {
		param, err := parseNumericParameter[int32](
			query.Get("latest"),
			WithParse[int32](parseInt32),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "latest", Err: err}, nil)
			return
		}

		latestParam = param
	} else {
	}
	result, err := c.service.PostMessagesPerUser(r.Context(), usernameParam, authorizationParam, payloadParam, latestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// PostRegister - 
func (c *MinitwitAPIController) PostRegister(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var payloadParam RegisterRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&payloadParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertRegisterRequestRequired(payloadParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertRegisterRequestConstraints(payloadParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	var latestParam int32
	if query.Has("latest") {
		param, err := parseNumericParameter[int32](
			query.Get("latest"),
			WithParse[int32](parseInt32),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "latest", Err: err}, nil)
			return
		}

		latestParam = param
	} else {
	}
	result, err := c.service.PostRegister(r.Context(), payloadParam, latestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
