// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Minitwit API
 *
 * Minitwit API
 *
 * API version: 1.0
 */

package openapi




type Message struct {

	// Text content of the message
	Content string `json:"content,omitempty"`

	// Publication date/time of the message
	PubDate string `json:"pub_date,omitempty"`

	// Username of the message author
	User string `json:"user,omitempty"`
}

// AssertMessageRequired checks if the required fields are not zero-ed
func AssertMessageRequired(obj Message) error {
	return nil
}

// AssertMessageConstraints checks if the values respects the defined constraints
func AssertMessageConstraints(obj Message) error {
	return nil
}
