// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Minitwit API
 *
 * Minitwit API
 *
 * API version: 1.0
 */

package openapi




type RegisterRequest struct {

	// Username
	Username string `json:"username"`

	// Email address
	Email string `json:"email"`

	// Password
	Pwd string `json:"pwd"`
}

// AssertRegisterRequestRequired checks if the required fields are not zero-ed
func AssertRegisterRequestRequired(obj RegisterRequest) error {
	elements := map[string]interface{}{
		"username": obj.Username,
		"email": obj.Email,
		"pwd": obj.Pwd,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRegisterRequestConstraints checks if the values respects the defined constraints
func AssertRegisterRequestConstraints(obj RegisterRequest) error {
	return nil
}
