// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Minitwit API
 *
 * Minitwit API
 *
 * API version: 1.0
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	MinitwitAPIService := openapi.NewMinitwitAPIService()
	MinitwitAPIController := openapi.NewMinitwitAPIController(MinitwitAPIService)

	router := openapi.NewRouter(MinitwitAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
