apiVersion: 1
groups:
    - orgId: 1
      name: Healthcheck
      folder: Alerts
      interval: 1m
      rules:
        - uid: cflgop2cdg9a8c
          title: Web Down
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 120
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: up{job="minitwit_web"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: eq
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 2m
          isPaused: false
          notification_settings:
            receiver: Web Down Discord Webhook
        - uid: bflgqzjdk7ldsc
          title: Api Down
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: up{job="minitwit"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: eq
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 2m
          isPaused: false
          notification_settings:
            receiver: Api Down Discord Webhook
