apiVersion: 1
contactPoints:
    - orgId: 1
      name: Api Down Discord Webhook
      receivers:
        - uid: bflgr4kepsiyod
          type: discord
          settings:
            message: '@everyone Api Service is down!'
            title: Api
            url: https://discord.com/api/webhooks/1492115087731986433/KIxRzQHCx737Lx20vJdAO1K5tNJCXyZkSzdM_dwUVzZBdwRY_nfyq479hLMX2Kjhjp4L
            use_discord_username: false
          disableResolveMessage: false
    - orgId: 1
      name: Web Down Discord Webhook
      receivers:
        - uid: eflgokynvkb28d
          type: discord
          settings:
            message: '@everyone Web Service is down!'
            title: Web
            url: https://discord.com/api/webhooks/1492115087731986433/KIxRzQHCx737Lx20vJdAO1K5tNJCXyZkSzdM_dwUVzZBdwRY_nfyq479hLMX2Kjhjp4L
            use_discord_username: true
          disableResolveMessage: false
