apiVersion: 1
contactPoints:
    - orgId: 1
      name: Api Down Discord Webhook
      receivers:
        - uid: bflgr4kepsiyod
          type: discord
          settings:
            message: '@everyone Api Service is down!'
            title: Api
            url: $__env{DISCORD_WEBHOOK_URL}
            use_discord_username: false
          disableResolveMessage: false
    - orgId: 1
      name: Web Down Discord Webhook
      receivers:
        - uid: eflgokynvkb28d
          type: discord
          settings:
            message: '@everyone Web Service is down!'
            title: Web
            url: $__env{DISCORD_WEBHOOK_URL}
            use_discord_username: true
          disableResolveMessage: false
