---
name: CI/CD Pipeline Production Server

on:
  push:
    # Run workflow every time something is pushed to the main branch
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
            go-version: '1.25'  

      - name: Quality checks - Static analysis
        run: make all

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      # TODO Get confirmation about this split
      - name: Build and push minitwitapiimage
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile.api
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/minitwitapiimage:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwitapiimage:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwitapiimage:webbuildcache,mode=max
      
      # TODO Get confirmation about this split
      - name: Build and push minitwitwebimage
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile.web
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/minitwitwebimage:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwitwebimage:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwitwebimage:webbuildcache,mode=max

      - name: Upload docker-compose.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: |
            docker-compose.yml
            docker-compose.monitoring.yml
          target: "/home/vagrant/app/"

      - name: Pull images and deploy to test server
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/vagrant/app
            docker compose -f docker-compose.yml -f docker-compose.monitoring.yml pull
            docker compose -f docker-compose.yml -f docker-compose.monitoring.yml up -d --remove-orphans

      # - name: Actions Status Discord
      #   uses: sarisia/actions-status-discord@v1.16.0
